### ISSUE TITLE
Tracker doesn't list all libraries, even though tracked?

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#74]
If I search for cyrus-sasl at https://abi-laboratory.pro/tracker/, it returns nothing. However, you do have: https://abi-laboratory.pro/?view=timeline&l=cyrus-sasl

**Comment by lvc** [comment]
Hi,

This is fixed. Thank you.

I'm currently working on repairing the project after a crash of compute server storage (since April 4).

Need some time (~months) to start tracking updates again.

If you need updated reports for some particular library(ies) please let me know (E-mail, bug, etc.).

Thanks.

**Comment by nehaljwani** [comment]
Thank you very much.
